import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";
import MobileFooter from "@/components/mobileFooter";
import Spacer from "@/components/spacer";


export const metadata: Metadata = {
  title: "DigiZone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Navbar />
        {/* <Spacer /> */}
        {children}
        <Footer />
        <MobileFooter />
      </body>
    </html>
  );
}
